version: "3.8"

services:
  web:
    build: .
    command: gunicorn api_games.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
      - static_volume:/code/staticfiles
    expose:
      - 8000

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    volumes:
      - static_volume:/static
    ports:
      - "80:80"

volumes:
  static_volume:
