version: "3.8"

services:
  web:
    build: .
    command: gunicorn api_games.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    expose:
      - 8000
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./staticfiles:/static
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
